In [2]:
%matplotlib inline

from matplotlib import pyplot as plt
import matplotlib.mlab as mlab
import csv
from scipy.stats import norm
import numpy as np
import scipy.stats as stats
import pandas as pd
from mpl_toolkits.mplot3d import axes3d
import seaborn as sns
from sklearn.cluster import DBSCAN


In [3]:
data = open('../data/data.csv', 'r').readlines()
fieldnames = ['x', 'y', 'z', 'unmasked', 'synapses']
reader = csv.reader(data)
reader.next()

rows = [[int(col) for col in row] for row in reader]

In [4]:
df = pd.DataFrame(rows)

In [5]:
df.columns = ['x', 'y', 'z', 'unmasked', 'synDen']

In [6]:
df = df[df.unmasked != 0]
df = df[df.synDen != 0]

In [8]:
df['synDen'] = df['synDen']/df['unmasked']
#data = df['synDen'].reshape(-1,1)
data = df[['x', 'y', 'z', 'synDen']]
data = data.as_matrix().astype("float32", copy = False)
print data



[[  1.90000000e+01   1.36900000e+03   6.10000000e+02   7.61636443e-08]
 [  1.90000000e+01   1.36900000e+03   1.05400000e+03   4.80285038e-08]
 [  1.90000000e+01   1.40800000e+03   6.10000000e+02   6.03652666e-08]
 ..., 
 [  4.19200000e+03   3.00700000e+03   8.32000000e+02   7.20427593e-08]
 [  4.19200000e+03   3.04600000e+03   8.32000000e+02   4.80285038e-08]
 [  4.19200000e+03   3.08500000e+03   8.32000000e+02   9.85748372e-08]]


In [34]:
dbsc = DBSCAN(eps = 55, min_samples = 1115).fit(data) 

In [35]:
labels = dbsc.labels_  
print labels
print len(df)

l = []
for i in range(0,len(labels)):
    if(labels[i] not in l):
        l.append(labels[i])
        
print len(l)


[-1 -1 -1 ..., -1 -1 -1]
50180
1
